engines:
  pep8:
    enabled: true

  csslint:
    enabled: true

  duplication:
    enabled: true
    languages:
      - javascript:
      - python:

  eslint:
    enabled: true

  fixme:
    enabled: true

  markdownlint:
    enabled: true

ratings:
   paths:
   - "**.css"
   - "**.js"
   - "**.md"
   - "**.py"
   - "**.sh"

exclude_paths:
  - jarbas/core/migrations/
