sudo: false
dist: trusty

language: python
python:
  - 3.5

addons:
    postgresql: "9.6"

services:
    - postgresql

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

install:
  - psql -U postgres -c 'create database "jarbas";'
  - nvm install 6
  - nvm use 6
  - npm install -g elm
  - npm install -g elm-test
  - npm install -g elm-doc-test
  - npm install
  - pip install -r requirements.txt coveralls

before_script:
  - python manage.py migrate
  - travis_wait 60 npm run assets
  - python manage.py collectstatic --no-input

script:
  - coverage run manage.py test -v 3
  - cd jarbas/frontend/
  - elm-doc-test
  - elm-test tests/Doc/Main.elm
  - cd ../../

after_success:
  - coveralls
