sudo: false
language: python
python:
  - 3.5
services:
    - postgresql

branches:
  only:
    - master

install:
  - psql -c 'create database jarbas;' -U postgres
  - nvm install 6
  - nvm use 6
  - npm install
  - pip install -r requirements.txt coveralls

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

before_script:
  - python manage.py migrate
  - travis_wait 60 npm run assets
  - python manage.py collectstatic --no-input

script:
  - npm test
  - coverage run manage.py test -v 3

after_success:
  - coveralls
