sudo: false
dist: trusty

language: python
python:
  - 3.5

addons:
    postgresql: "9.6"

services:
    - postgresql

env:
  - DATABASE_URL="postgres://postgres@localhost/jarbas"

install:
  - psql -U postgres -c 'create database "jarbas";'
  - nvm install 6
  - nvm use 6
  - npm install -g yarn
  - yarn install
  - pip install -r requirements.txt coveralls

before_script:
  - yarn assets
  - python manage.py migrate
  - python manage.py collectstatic --no-input

script:
  - travis_wait 60 yarn test
  - coverage run manage.py test -v 3

after_success:
  - coveralls
