version: '3'
services:

  django:
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://jarbas:mysecretpassword@postgres/jarbas
      - SECRET_KEY=my_dear_secret
      - DEBUG=True
    ports:
      - "8000:8000"

  tasks:
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://jarbas:mysecretpassword@postgres/jarbas
      - SECRET_KEY=my_dear_secret
      - DEBUG=True

  elm:
    volumes:
      - ./jarbas:/code/jarbas

  postgres:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"
