version: '2'
services:
  jarbas:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - "staticfiles:/code/staticfiles"
       - "assets:/code/jarbas/frontend/"
    depends_on:
       - elm

  elm:
    build:
      context: .
      dockerfile: Dockerfile-elm
    volumes:
      - "assets:/assets/"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - "staticfiles:/opt/jarbas/staticfiles"
    ports:
      - "80:80"
    depends_on:
      - "jarbas"
volumes:
  assets:
    external: false
  staticfiles:
    external: false
