version: '3'
services:

  django:
    image: datasciencebr/jarbas-backend
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - AMAZON_S3_BUCKET=serenata-de-amor-data
      - AMAZON_S3_REGION=s3-sa-east-1
      - AMAZON_S3_CEAPTRANSLATION_DATE=2016-08-08
      - CELERY_BROKER_URL=amqp://guest:guest@queue/
    depends_on:
      - elm
      - tasks
    volumes:
      - "./contrib/data:/mnt/data"

  tasks:
    image: datasciencebr/jarbas-backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@queue/
    depends_on:
      - queue
    entrypoint: ["/bin/sh", "-c"]
    command: ["celery", "worker", "--app", "jarbas"]

  elm:
    image: datasciencebr/jarbas-frontend


  queue:
    image: rabbitmq:3.6.11-alpine
