version: '3'
services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       - DATABASE_URL=postgres://jarbas:mysecretpassword@postgres/jarbas
       - ALLOWED_HOSTS=localhost,127.0.0.1
       - AMAZON_S3_BUCKET=serenata-de-amor-data
       - AMAZON_S3_REGION=s3-sa-east-1
       - AMAZON_S3_CEAPTRANSLATION_DATE=2016-08-08
    depends_on:
       - elm
       - postgres

  elm:
    build:
      context: .
      dockerfile: Dockerfile-elm

  postgres:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas
