version: '3'
services:
    proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    networks:
      - backend
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy/certs:/etc/nginx/certs
      - proxy/vhost:/etc/nginx/vhost.d
      - proxy/public:/usr/share/nginx/html
      - ./proxy/nginx.tmpl:/app/nginx.tmpl

  proxy-certs:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy/certs:/etc/nginx/certs:rw
      - proxy/vhost:/etc/nginx/vhost.d
      - proxy/public:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: proxy

  django:
    env_file:
      - .env
    environment:
       - DEBUG=False
    depends_on:
       - memcached
    expose:
      - "8000"
    volumes:
      - assets:/code/staticfiles
    entrypoint: ["gunicorn", "jarbas.wsgi:application", "--reload", "--bind", "0.0.0.0:8000", "--workers", "4"]
    command: []

  tasks:
    env_file:
      - .env
    environment:
       - DEBUG=False

  elm:
    command: ["npm", "run", "assets"]
    volumes:
      - assets:/code/jarbas/frontend/static

  postgres:
    expose:
      - "5432"

  memcached:
    image: memcached:1.5.1-alpine

  nginx:
    image: datasciencebr/jarbas-server
    networks:
      - backend
    depends_on:
      - django
    volumes:
      - assets:/code/staticfiles
    environment:
      VIRTUAL_HOST: jarbas.serenatadeamor.org
      LETSENCRYPT_HOST: jarbas.serenatadeamor.org
      LETSENCRYPT_EMAIL: jarbas@serenatadeamor.org
      HTTPS_METHOD: redirect
      VIRTUAL_PROTO: http

volumes:
  assets:
  proxy:

networks:
  backend:
    driver: bridge
