version: '2'
services:
  jarbas:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - "staticfiles:/code/staticfiles"
       - "assets:/code/jarbas/frontend/"
    environment:
       - SECRET_KEY=lets-rock
       - DATABASE_URL=postgres://jarbas:mysecretpassword@db/jarbas
    depends_on:
       - elm
       - db

  elm:
    build:
      context: .
      dockerfile: Dockerfile-elm
    volumes:
      - "assets:/assets/"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - "staticfiles:/opt/jarbas/staticfiles"
    ports:
      - "80:80"
    depends_on:
      - "jarbas"

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas
volumes:
  assets:
    external: false
  staticfiles:
    external: false
