version: '3'
services:

  django:
    env_file:
      - .env
    environment:
       - DEBUG=False
    depends_on:
       - memcached
    expose:
      - "8000"
    volumes:
      - assets:/code/staticfiles
    entrypoint: ["gunicorn", "jarbas.wsgi:application", "--reload", "--bind", "0.0.0.0:8000", "--workers", "4"]
    command: []

  tasks:
    env_file:
      - .env
    environment:
       - DEBUG=False

  elm:
    command: ["npm", "run", "assets"]
    volumes:
      - assets:/code/jarbas/layers/static

  postgres:
    expose:
      - "5432"

  memcached:
    image: memcached:1.5.1-alpine

  nginx:
    image: datasciencebr/jarbas-server
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - assets:/code/staticfiles

volumes:
  assets:
