---
- hosts: 127.0.0.1
  gather_facts: yes

  pre_tasks:
    - name: up new droplet
      digital_ocean:
        state: active
        command: droplet
        image_id: ubuntu-16-04-x64
        name: serenata-update
        region_id: nyc1
        size_id: s-6vcpu-16gb
        unique_name: yes
      register: tmp

  post_tasks:
    - name: destroy droplet
      digital_ocean:
        state: deleted
        id: "{{ tmp.droplet.id | int }}"
