---
- hosts: 127.0.0.1

  pre_tasks:
    - name: create new ssh keys
      digital_ocean:
        state: present
        command: ssh
        name: serenata-update
        ssh_pub_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      register: ssh_public_key

    - name: create new droplet
      digital_ocean:
        state: active
        command: droplet
        image_id: ubuntu-16-04-x64
        name: serenata-update
        region_id: nyc1
        size_id: s-6vcpu-16gb
        unique_name: yes
        ssh_key_ids:
          - "{{ ssh_public_key.ssh_key.id | int }}"
      register: tmp

    - name: wait for ssh
      local_action: wait_for host={{ tmp.droplet.ip_address }} port=22 delay=60 timeout=320 state=started

  post_tasks:
    - name: destroy droplet
      digital_ocean:
        state: deleted
        id: "{{ tmp.droplet.id | int }}"
    - name: destroy ssh keys
      digital_ocean:
        state: absent
        command: ssh
        name: serenata-update
